name: "CI/CD Pipeline for LMS front-end"
on: 
  push:
    branches:
      - 'main'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3   # clone main branch

      - uses: actions/setup-node@v3 # to convert sass into css we need node
        with:
          node-version: 18

      - run: npm install -g sass

      - run: sass scss:css

      - run: mkdir dist

      - run: cp -r css pages js index.html dist/

      - run: zip -r dist.zip dist/

      - run: ls -la .